version: 2

project_name: vyconfigure

env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
    binary: vyconfigure

release:
  prerelease: auto

archives:
  - formats: [ 'binary' ]
