version: 2

env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
    binary: vyconfigure

release:
  prerelease: auto

archives:
  - format: binary
