---
name: Check

on:
  workflow_dispatch:
  pull_request:

jobs:   
  build:    
    runs-on: ubuntu-24.04           
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v5

    - name: Lint with golangci-lint
      uses: golangci/golangci-lint-action@v8

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Run GoReleaser check
      uses: goreleaser/goreleaser-action@v6.4.0
      with:
        version: 2.11.0
        args: build --skip=validate --snapshot

    - name: Test
      run: make test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vyconfigure
        path: dist/*
