---
name: Build/Publish

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout the code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6.3.0
      with:
        version: 2.11.0
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
